# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghostwriter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='ocr_text',
            field=models.TextField(blank=True, null=True, verbose_name='OCR'),
        ),
    ]
