# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 23:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghostwriter', '0002_lecture_ocr_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'CAPTURE'), (1, 'REGISTER')])),
                ('state', models.IntegerField(choices=[(0, 'RUNNING'), (1, 'STOPPED')])),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('task_id', models.CharField(max_length=255, verbose_name='TaskID')),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='ocr_json',
            field=models.TextField(blank=True, null=True, verbose_name='JSON'),
        ),
    ]
