# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 07:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ghostwriter', '0004_lecture_is_parsed'),
    ]

    operations = [
        migrations.CreateModel(
            name='OCRTaskRecord',
            fields=[
                ('taskrecord_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ghostwriter.TaskRecord')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_records', to='ghostwriter.Lecture')),
            ],
            bases=('ghostwriter.taskrecord',),
        ),
        migrations.AlterModelOptions(
            name='taskrecord',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterField(
            model_name='taskrecord',
            name='state',
            field=models.IntegerField(choices=[(0, 'RUNNING'), (1, 'DONE'), (2, 'FAIL')]),
        ),
        migrations.AlterField(
            model_name='taskrecord',
            name='type',
            field=models.IntegerField(choices=[(0, 'CAPTURE'), (1, 'ANALYSIS'), (2, 'OCR'), (3, 'REGISTER')]),
        ),
    ]
